import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "OpenAI",
  display: "group",
  collapsed: true,
  pages: ["gpt-image-1","gpt-image-1-5","gpt-image-2","gpt-image-2-5-flare","gpt-image-2-5-sunburst"],
});
