import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Kling AI",
  display: "group",
  collapsed: true,
  pages: ["kling-2-6","kling-3-0"],
});
