import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Alibaba",
  display: "group",
  collapsed: true,
  pages: ["happyhorse-1-1","qwen-image-2-1","qwen-image-3-0-pro","wan-2-6","wan-2-7","wan-2-7-image","wan-2-7-image-pro","wan-3-0","z-image-turbo"],
});
