import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Meta",
  display: "group",
  collapsed: true,
  pages: ["muse-image-1-0"],
});
