import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Black Forest Labs",
  display: "group",
  collapsed: true,
  pages: ["flux-2-flex","flux-2-max","flux-2-pro","flux-kontext-pro","flux-pro-1-1","flux-pro-1-1-ultra"],
});
