import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Prodia",
  icon: "<svg viewBox=\"0 0 24 24\" width=\"100%\" height=\"100%\" fill=\"currentColor\" fill-rule=\"evenodd\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M11 3h2.5a9 9 0 010 18H11v-3h2.5a6 6 0 000-12H11V3z\"/><path d=\"M8 3h3v3H8zM5 6h3v3H5zM8 9h3v3H8zM5 12h3v3H5zM8 15h3v3H8zM2 15h3v3H2zM5 18h3v3H5z\"/></svg>",
  display: "group",
  collapsed: true,
  pages: ["flux-fast-schnell"],
});
