import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Prodia",
  display: "group",
  collapsed: true,
  pages: ["flux-fast-schnell"],
});
