import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "Recraft",
  display: "group",
  collapsed: true,
  pages: ["recraft-v3"],
});
