import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "ByteDance",
  display: "group",
  collapsed: true,
  pages: ["seedance-1-5-pro","seedance-2-0","seedance-2-0-fast","seedance-2-0-mini","seedance-2-5","seedream-4-5","seedream-5-0","seedream-5-0-pro"],
});
