import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "MiniMax",
  display: "group",
  collapsed: true,
  pages: ["hailuo-2-3","hailuo-2-3-fast","minimax-h3","minimax-h3-max"],
});
