import { defineMeta } from "blume";

// Generated by scripts/generate-model-pages.mjs.
export default defineMeta({
  title: "xAI",
  display: "group",
  collapsed: true,
  pages: ["grok-imagine-image","grok-imagine-image-2-0","grok-imagine-video"],
});
